### ISSUE TITLE
Use named pipes on Windows?

### ISSUE THREAD

**Issue by davclark** [arhea/harbor-master#7]
I must admit to being slightly mistified as to how it works, but many systems support "named pipes" (or npipe:// URLs) on windows to bypass HTTPS issues and the need to get certificates for TLS over HTTP.

For example, dockerode will work if you set `socketPath` to `//./pipe/docker_engine`, and somehow that works, see: https://github.com/apocas/dockerode/issues/290

Setting `path` in harbor-master to the same does not work. One fundamental point of my mystification is that I don't actually understand the meaning of the `//` in docker for windows. It seems to have been a temporary measure in referring to moby paths, that quickly fell out of usage again... except in this one case.

**Comment by davclark** [comment]
Cleaning up my open issues...

**Comment by lukewis** [comment]
How did you solve this @davclark ?  I keep getting a "page not found" message when using this method.
```
const client = docker.Client({
        socket: "//./pipe/docker_engine"
    });

    client.images().inspect(`${svcImageName}:${svcImageTag}`).then((res: any) => {
        const json = res.response.toJSON();
        console.log(json);
    }).catch(console.error);
```

**Comment by davclark** [comment]
This was quite a while ago, and the repositories have actually been deleted... but my recollection is that we wrote our own code in node that shelled out to the relevant docker commands.

**Comment by lukewis** [comment]
I appreciate the response!  Apologies for resurrecting an ancient thread.
